project_name: iam
before:
  hooks:
    - go generate ./...
builds:
  - id: authorizer
    main: ./lambda/authorizer/authorizer.go
    binary: authorizer
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
